### ISSUE TITLE
Distance between bars

### ISSUE THREAD

**Issue by kentforth** [VitorLuizC/vue-burger-button#7]
Hi!
Your button is cool .
 **How can I change distance between bars?**
there is only height and width of bars, but there is no distance option

**Comment by VitorLuizC** [comment]
Sorry to took so long to answer you. Today you can only change distance using CSS `translateY` property. But remember to also update `translateY` when active (close mode).

That's current applied styles:
```html
<style>
.burguer-button > .bar:nth-child(1) {
  transform: translateY(-75%);
}

.burguer-button  > .bar:nth-child(3) {
  transform: translateY(75%);
}

.burguer-button.-active > .bar:nth-child(1) {
  transform: translateY(100%) rotate(45deg);
}

.burguer-button.-active > .bar:nth-child(3) {
  transform: translateY(-100%) rotate(-45deg);
}
</style>
```

**Comment by kentforth** [comment]
Thanx!
